server:
  port: 9191
spring:
  data:
    mongodb:
      host: localhost
      database: Payment
  application:
    name: payment-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
